
var config = {
    texts: [
        "To My Dear 文霞",    
        "面朝大海",
        "纵使泪别二十七",
        "童颜仍需过六一",
        "童颜",
        "光阴需要有印记",
        "年龄背锅莫在意",
        "愿虽一直被你欺",
        "能换呲牙笑嘻嘻",
        "闲庭信步",
        "趴地堵门能吃鸡",
        "还能再修热水器",
        "入睡只需把眼咪",
        "让梦随风夜郎西",
        "他日生成婚礼纪",
        "缺个女主薛薛你",
        "Yours",
        "Always",
        "Old Eddie",
        "真爱永恒",
    ],
    imgs: {
        "面朝大海": "./imgs/IMG_8810.JPG",
        "童颜": "./imgs/IMG_8791(20220608-132026).PNG",
        "真爱永恒": "./imgs/IMG_8972(20220517-232712).JPG",
        "闲庭信步": "./imgs/IMG_8929.JPG",
    },
    desc: {
        turn_on: "别点我",
        play: "辣个男银",
        bannar_coming: "Ta Lǎi Le",
        balloons_flying: "纯嘴吹的",
        cake_fadein: "芋泥夹心安排上",
        light_candle: "逐渐年轻的小火焰",
        wish_message: "生日快乐",
        story: "Love Letter FOR YOU",
    }
};
